### ISSUE TITLE
Fails on the 10th page, most times

### ISSUE THREAD

**Issue by somik123** [robinovitch61/webtoon-dl#15]
Read and checkbox the following by putting an "x" in the brackets like `- [x]` before submitting this bug report:

- [x] I have searched existing issues, opened and closed, for existing solutions to my problem
- [x] I understand that I have to fill out all of the following or risk my issue being closed and locked

**What you ran, all the output, and the entire error message, if any**
```
somik@oldie:~/webtoons/Doom Breaker$ ~/webtoons/.bin/webtoon-dl --eps-per-file=1 --format cbz https://www.webtoons.com/en/action/doom-breaker/list?title_no=3197
scanning all pages to get all episode links
https://www.webtoons.com/en/action/doom-breaker/list?title_no=3197&page=1
https://www.webtoons.com/en/action/doom-breaker/list?title_no=3197&page=2
https://www.webtoons.com/en/action/doom-breaker/list?title_no=3197&page=3
https://www.webtoons.com/en/action/doom-breaker/list?title_no=3197&page=4
https://www.webtoons.com/en/action/doom-breaker/list?title_no=3197&page=5
https://www.webtoons.com/en/action/doom-breaker/list?title_no=3197&page=6
https://www.webtoons.com/en/action/doom-breaker/list?title_no=3197&page=7
https://www.webtoons.com/en/action/doom-breaker/list?title_no=3197&page=8
https://www.webtoons.com/en/action/doom-breaker/list?title_no=3197&page=9
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x683ca0]

goroutine 1 [running]:
github.com/anaskhan96/soup.findAllofem.func1(0x414e68?, {0xc000022290?, 0x1, 0x1}, 0x0?)
        /home/runner/go/pkg/mod/github.com/anaskhan96/soup@v1.2.5/soup.go:534 +0x1c0
github.com/anaskhan96/soup.findAllofem(0xc000169568?, {0xc000022290, 0x1, 0x1}, 0x0)
        /home/runner/go/pkg/mod/github.com/anaskhan96/soup@v1.2.5/soup.go:538 +0xe3
github.com/anaskhan96/soup.Root.FindAll({0x0, {0x0, 0x0}, {0x7ba1a0, 0xc000010438}}, {0xc000022290?, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/anaskhan96/soup@v1.2.5/soup.go:283 +0x7a
main.getEpisodeLinksForPage({0xc0002d6af0?, 0xc0002d6aa0?})
        /home/runner/go/pkg/mod/github.com/robinovitch61/webtoon-dl@v0.0.10/main.go:205 +0x236
main.getAllEpisodeLinks({0x7ffc2c5326df, 0x42})
        /home/runner/go/pkg/mod/github.com/robinovitch61/webtoon-dl@v0.0.10/main.go:268 +0x19a
main.getEpisodeBatches({0x7ffc2c5326df, 0x42}, 0x0, 0x7fffffffffffffff, 0x1)
        /home/runner/go/pkg/mod/github.com/robinovitch61/webtoon-dl@v0.0.10/main.go:226 +0x90
main.main()
        /home/runner/go/pkg/mod/github.com/robinovitch61/webtoon-dl@v0.0.10/main.go:422 +0xdc
```

**Expected behavior**
Download all the pages and continue to download the rest of the content (which it did once)

**Screenshots**
Also tried escaping the url string:
![2024-10-13_001951](https://github.com/user-attachments/assets/10fe39fd-539a-4204-be1a-af9c4ce95215)

**Complete the following information:**
 - OS [e.g. Mac, Windows, Ubuntu, Arch, NixOS, etc.]: Ubuntu (headless)
 - Version [e.g. v0.0.5]: 22.04.5 LTS (Jammy Jellyfish)
 - Available space on disk [e.g. 10GB]: 94G
 - RAM [e.g. 8GB]: 4GB

**Comment by somik123** [comment]
Decided to write my own downloader in python.
